# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 9091
    context-path: /jeefast
#fileinfo
upload:
  flespath: D:\upload
# mysql
spring:
    #  dev|test|pro
    profiles:
        active: dev
    # jacksontime format化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources:
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: false  #
        database: 0
        host: localhost
        port: 16379
        password:       # password
        timeout: 6000  #
        pool:
            max-active: 1000  #
            max-wait: -1      #
            max-idle: 10      #
            min-idle: 5       #

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Dao.xml
  #
  typeAliasesPackage: cn.jeefast.system.entity , cn.jeefast.modules.**.entity
  global-config:
    #
    id-type: 0
    #
    field-strategy: 2
    #
    db-column-underline: true
    #
    refresh-mapper: true
    #
    #capital-mode: true
    #
    #key-generator: cn.jeefast.xxx
    #deleteconfiguration
    logic-delete-value: 0
    logic-not-delete-value: 1
    #
    #meta-object-handler: cn.jeefast.xxx
    #
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

